- hosts: localhost
  connection: local
  
  tasks:
    - import_tasks: asdf.yaml
      tags:
        - asdf
        
    - import_tasks: files.yaml
      tags:
        - files
 
    - import_tasks: pip.yaml
      tags:
        - pip

    - import_tasks: npm.yaml
      tags:
        - npm

    - import_tasks: go.yaml
      tags:
        - go

    - import_tasks: apt.yaml
      tags:
        - apt

